defaults: &defaults
  adapter:  mysql
  username: root
  password: admin
  host: localhost
  encoding: utf8
  pool: 5

development:
  <<:       *defaults
  database: whylt

test:
  <<:       *defaults
  database: whylt_test

staging:
  <<:       *defaults
  database: chartered_staging

production:
  database: whylt_production
  adapter:  mysql
  username: root
  password: admin
  host: localhost
  encoding: utf8
